; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- 1. THE MASTER FLIGHT BUILD ---
[env:flightcode]
platform = teensy
board = teensy41
framework = arduino

; Compile everything in src/, but IGNORE the hardware_tests folder entirely
build_src_filter = +<*> -<../hardware_tests/> 

; --- 2. THE DEVELOPER TEST ENVIRONMENT ---
[env:testcode]
platform = teensy
board = teensy41
framework = arduino

; IGNORE the master src/ folder, and ONLY compile this specific test file
; Developers will change "test_baro.cpp" to whatever test they are running locally
build_src_filter = -<*> +<../hardware_tests/test_gps.c>